// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package com.shattered.networking.proto;

public final class PacketOuterClass {
  private PacketOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code shattered.protocol.Opcode}
   */
  public enum Opcode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * After hours of contemplating ripping my hair out, opcode 0 on an empty packet results in a zero length packet, and is therefore ignored.
     * </pre>
     *
     * <code>INVALID_OPCODE = 0;</code>
     */
    INVALID_OPCODE(0),
    /**
     * <pre>
     *Universal Packets
     * </pre>
     *
     * <code>U_Messages = 1;</code>
     */
    U_Messages(1),
    /**
     * <code>U_Ping = 2;</code>
     */
    U_Ping(2),
    /**
     * <code>U_ServerPerformance = 3;</code>
     */
    U_ServerPerformance(3),
    /**
     * <code>U_EO_Messages = 27;</code>
     */
    U_EO_Messages(27),
    /**
     * <pre>
     *Proxy Packets
     * </pre>
     *
     * <code>Proxy_Messages = 28;</code>
     */
    Proxy_Messages(28),
    /**
     * <code>P_OpenConnection = 29;</code>
     */
    P_OpenConnection(29),
    /**
     * <code>P_CloseConnection = 30;</code>
     */
    P_CloseConnection(30),
    /**
     * <code>P_ServerAvailability = 31;</code>
     */
    P_ServerAvailability(31),
    /**
     * <code>P_TransmitAccount = 32;</code>
     */
    P_TransmitAccount(32),
    /**
     * <code>P_RequestRealm = 33;</code>
     */
    P_RequestRealm(33),
    /**
     * <code>P_TransferConnection = 34;</code>
     */
    P_TransferConnection(34),
    /**
     * <code>P_ServerTransferResponse = 35;</code>
     */
    P_ServerTransferResponse(35),
    /**
     * <code>P_RequestNewTransferConnection = 36;</code>
     */
    P_RequestNewTransferConnection(36),
    /**
     * <code>P_TransferToWorld = 37;</code>
     */
    P_TransferToWorld(37),
    /**
     * <code>P_TransferToRealm = 38;</code>
     */
    P_TransferToRealm(38),
    /**
     * <code>P_TransferWorldToRealm = 39;</code>
     */
    P_TransferWorldToRealm(39),
    /**
     * <code>P_WorldCharacterInformation = 40;</code>
     */
    P_WorldCharacterInformation(40),
    /**
     * <code>Proxy_EO_Messages = 51;</code>
     */
    Proxy_EO_Messages(51),
    /**
     * <pre>
     *Sharding Packets (Central)
     * </pre>
     *
     * <code>Sharding_Messages = 52;</code>
     */
    Sharding_Messages(52),
    /**
     * <code>S_Register = 53;</code>
     */
    S_Register(53),
    /**
     * <code>S_Unregister = 54;</code>
     */
    S_Unregister(54),
    /**
     * <code>S_ConnectionInfo = 55;</code>
     */
    S_ConnectionInfo(55),
    /**
     * <code>S_RequestConnectionInfo = 56;</code>
     */
    S_RequestConnectionInfo(56),
    /**
     * <code>S_OpenConnection = 57;</code>
     */
    S_OpenConnection(57),
    /**
     * <code>S_WorldInformation = 58;</code>
     */
    S_WorldInformation(58),
    /**
     * <code>S_UpdateWorldList = 59;</code>
     */
    S_UpdateWorldList(59),
    /**
     * <code>S_UpdateWorldEntry = 60;</code>
     */
    S_UpdateWorldEntry(60),
    /**
     * <code>Sharding_EO_Messages = 76;</code>
     */
    Sharding_EO_Messages(76),
    /**
     * <pre>
     *Channel Messages (Shared between (world/realm) and channel)
     * </pre>
     *
     * <code>Channel_Messages = 77;</code>
     */
    Channel_Messages(77),
    /**
     * <code>Channel_EO_Messages = 101;</code>
     */
    Channel_EO_Messages(101),
    /**
     * <pre>
     *Shared Messages (Shared between realm and world)
     * </pre>
     *
     * <code>Shared_Messages = 102;</code>
     */
    Shared_Messages(102),
    /**
     * <code>SMSG_CONNECTED = 103;</code>
     */
    SMSG_CONNECTED(103),
    /**
     * <code>SMSG_DISCONNECTED = 104;</code>
     */
    SMSG_DISCONNECTED(104),
    /**
     * <code>SMSG_ACCOUNT_INFORMATION = 105;</code>
     */
    SMSG_ACCOUNT_INFORMATION(105),
    /**
     * <code>CMSG_LOGIN_REQUEST = 106;</code>
     */
    CMSG_LOGIN_REQUEST(106),
    /**
     * <code>SMSG_LOGIN_RESPONSE = 107;</code>
     */
    SMSG_LOGIN_RESPONSE(107),
    /**
     * <code>CMSG_REQUEST_LOGOUT = 108;</code>
     */
    CMSG_REQUEST_LOGOUT(108),
    /**
     * <code>SMSG_LOGOUT = 109;</code>
     */
    SMSG_LOGOUT(109),
    /**
     * <code>SMSG_LOGOUT_WITH_RESPONSE = 110;</code>
     */
    SMSG_LOGOUT_WITH_RESPONSE(110),
    /**
     * <code>CMSG_REQUEST_FRIENDS = 111;</code>
     */
    CMSG_REQUEST_FRIENDS(111),
    /**
     * <code>CMSG_FRIENDS_LIST = 112;</code>
     */
    CMSG_FRIENDS_LIST(112),
    /**
     * <code>CMSG_PRIVATE_MESSAGE = 113;</code>
     */
    CMSG_PRIVATE_MESSAGE(113),
    /**
     * <code>SMSG_PRIVATE_MESSAGE = 114;</code>
     */
    SMSG_PRIVATE_MESSAGE(114),
    /**
     * <code>SMSG_FRIENDS_LIST = 115;</code>
     */
    SMSG_FRIENDS_LIST(115),
    /**
     * <code>SMSG_UPDATE_FRIEND = 116;</code>
     */
    SMSG_UPDATE_FRIEND(116),
    /**
     * <code>CMSG_ADD_FRIEND = 117;</code>
     */
    CMSG_ADD_FRIEND(117),
    /**
     * <code>CMSG_REMOVE_FRIEND = 118;</code>
     */
    CMSG_REMOVE_FRIEND(118),
    /**
     * <code>CMSG_IGNORE_CHARACTER = 119;</code>
     */
    CMSG_IGNORE_CHARACTER(119),
    /**
     * <code>SMSG_WORLD_LOGIN_TRANSFER = 120;</code>
     */
    SMSG_WORLD_LOGIN_TRANSFER(120),
    /**
     * <code>Shared_EO_Messages = 151;</code>
     */
    Shared_EO_Messages(151),
    /**
     * <pre>
     *Shattered Realm Messages
     * </pre>
     *
     * <code>Shattered_Realm_Messages = 152;</code>
     */
    Shattered_Realm_Messages(152),
    /**
     * <code>Shattered_Realm_EO_Messages = 251;</code>
     */
    Shattered_Realm_EO_Messages(251),
    /**
     * <pre>
     *Shattered World Messages
     * </pre>
     *
     * <code>Shattered_World_Messages = 252;</code>
     */
    Shattered_World_Messages(252),
    /**
     * <code>Shattered_World_EO_Messages = 401;</code>
     */
    Shattered_World_EO_Messages(401),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * After hours of contemplating ripping my hair out, opcode 0 on an empty packet results in a zero length packet, and is therefore ignored.
     * </pre>
     *
     * <code>INVALID_OPCODE = 0;</code>
     */
    public static final int INVALID_OPCODE_VALUE = 0;
    /**
     * <pre>
     *Universal Packets
     * </pre>
     *
     * <code>U_Messages = 1;</code>
     */
    public static final int U_Messages_VALUE = 1;
    /**
     * <code>U_Ping = 2;</code>
     */
    public static final int U_Ping_VALUE = 2;
    /**
     * <code>U_ServerPerformance = 3;</code>
     */
    public static final int U_ServerPerformance_VALUE = 3;
    /**
     * <code>U_EO_Messages = 27;</code>
     */
    public static final int U_EO_Messages_VALUE = 27;
    /**
     * <pre>
     *Proxy Packets
     * </pre>
     *
     * <code>Proxy_Messages = 28;</code>
     */
    public static final int Proxy_Messages_VALUE = 28;
    /**
     * <code>P_OpenConnection = 29;</code>
     */
    public static final int P_OpenConnection_VALUE = 29;
    /**
     * <code>P_CloseConnection = 30;</code>
     */
    public static final int P_CloseConnection_VALUE = 30;
    /**
     * <code>P_ServerAvailability = 31;</code>
     */
    public static final int P_ServerAvailability_VALUE = 31;
    /**
     * <code>P_TransmitAccount = 32;</code>
     */
    public static final int P_TransmitAccount_VALUE = 32;
    /**
     * <code>P_RequestRealm = 33;</code>
     */
    public static final int P_RequestRealm_VALUE = 33;
    /**
     * <code>P_TransferConnection = 34;</code>
     */
    public static final int P_TransferConnection_VALUE = 34;
    /**
     * <code>P_ServerTransferResponse = 35;</code>
     */
    public static final int P_ServerTransferResponse_VALUE = 35;
    /**
     * <code>P_RequestNewTransferConnection = 36;</code>
     */
    public static final int P_RequestNewTransferConnection_VALUE = 36;
    /**
     * <code>P_TransferToWorld = 37;</code>
     */
    public static final int P_TransferToWorld_VALUE = 37;
    /**
     * <code>P_TransferToRealm = 38;</code>
     */
    public static final int P_TransferToRealm_VALUE = 38;
    /**
     * <code>P_TransferWorldToRealm = 39;</code>
     */
    public static final int P_TransferWorldToRealm_VALUE = 39;
    /**
     * <code>P_WorldCharacterInformation = 40;</code>
     */
    public static final int P_WorldCharacterInformation_VALUE = 40;
    /**
     * <code>Proxy_EO_Messages = 51;</code>
     */
    public static final int Proxy_EO_Messages_VALUE = 51;
    /**
     * <pre>
     *Sharding Packets (Central)
     * </pre>
     *
     * <code>Sharding_Messages = 52;</code>
     */
    public static final int Sharding_Messages_VALUE = 52;
    /**
     * <code>S_Register = 53;</code>
     */
    public static final int S_Register_VALUE = 53;
    /**
     * <code>S_Unregister = 54;</code>
     */
    public static final int S_Unregister_VALUE = 54;
    /**
     * <code>S_ConnectionInfo = 55;</code>
     */
    public static final int S_ConnectionInfo_VALUE = 55;
    /**
     * <code>S_RequestConnectionInfo = 56;</code>
     */
    public static final int S_RequestConnectionInfo_VALUE = 56;
    /**
     * <code>S_OpenConnection = 57;</code>
     */
    public static final int S_OpenConnection_VALUE = 57;
    /**
     * <code>S_WorldInformation = 58;</code>
     */
    public static final int S_WorldInformation_VALUE = 58;
    /**
     * <code>S_UpdateWorldList = 59;</code>
     */
    public static final int S_UpdateWorldList_VALUE = 59;
    /**
     * <code>S_UpdateWorldEntry = 60;</code>
     */
    public static final int S_UpdateWorldEntry_VALUE = 60;
    /**
     * <code>Sharding_EO_Messages = 76;</code>
     */
    public static final int Sharding_EO_Messages_VALUE = 76;
    /**
     * <pre>
     *Channel Messages (Shared between (world/realm) and channel)
     * </pre>
     *
     * <code>Channel_Messages = 77;</code>
     */
    public static final int Channel_Messages_VALUE = 77;
    /**
     * <code>Channel_EO_Messages = 101;</code>
     */
    public static final int Channel_EO_Messages_VALUE = 101;
    /**
     * <pre>
     *Shared Messages (Shared between realm and world)
     * </pre>
     *
     * <code>Shared_Messages = 102;</code>
     */
    public static final int Shared_Messages_VALUE = 102;
    /**
     * <code>SMSG_CONNECTED = 103;</code>
     */
    public static final int SMSG_CONNECTED_VALUE = 103;
    /**
     * <code>SMSG_DISCONNECTED = 104;</code>
     */
    public static final int SMSG_DISCONNECTED_VALUE = 104;
    /**
     * <code>SMSG_ACCOUNT_INFORMATION = 105;</code>
     */
    public static final int SMSG_ACCOUNT_INFORMATION_VALUE = 105;
    /**
     * <code>CMSG_LOGIN_REQUEST = 106;</code>
     */
    public static final int CMSG_LOGIN_REQUEST_VALUE = 106;
    /**
     * <code>SMSG_LOGIN_RESPONSE = 107;</code>
     */
    public static final int SMSG_LOGIN_RESPONSE_VALUE = 107;
    /**
     * <code>CMSG_REQUEST_LOGOUT = 108;</code>
     */
    public static final int CMSG_REQUEST_LOGOUT_VALUE = 108;
    /**
     * <code>SMSG_LOGOUT = 109;</code>
     */
    public static final int SMSG_LOGOUT_VALUE = 109;
    /**
     * <code>SMSG_LOGOUT_WITH_RESPONSE = 110;</code>
     */
    public static final int SMSG_LOGOUT_WITH_RESPONSE_VALUE = 110;
    /**
     * <code>CMSG_REQUEST_FRIENDS = 111;</code>
     */
    public static final int CMSG_REQUEST_FRIENDS_VALUE = 111;
    /**
     * <code>CMSG_FRIENDS_LIST = 112;</code>
     */
    public static final int CMSG_FRIENDS_LIST_VALUE = 112;
    /**
     * <code>CMSG_PRIVATE_MESSAGE = 113;</code>
     */
    public static final int CMSG_PRIVATE_MESSAGE_VALUE = 113;
    /**
     * <code>SMSG_PRIVATE_MESSAGE = 114;</code>
     */
    public static final int SMSG_PRIVATE_MESSAGE_VALUE = 114;
    /**
     * <code>SMSG_FRIENDS_LIST = 115;</code>
     */
    public static final int SMSG_FRIENDS_LIST_VALUE = 115;
    /**
     * <code>SMSG_UPDATE_FRIEND = 116;</code>
     */
    public static final int SMSG_UPDATE_FRIEND_VALUE = 116;
    /**
     * <code>CMSG_ADD_FRIEND = 117;</code>
     */
    public static final int CMSG_ADD_FRIEND_VALUE = 117;
    /**
     * <code>CMSG_REMOVE_FRIEND = 118;</code>
     */
    public static final int CMSG_REMOVE_FRIEND_VALUE = 118;
    /**
     * <code>CMSG_IGNORE_CHARACTER = 119;</code>
     */
    public static final int CMSG_IGNORE_CHARACTER_VALUE = 119;
    /**
     * <code>SMSG_WORLD_LOGIN_TRANSFER = 120;</code>
     */
    public static final int SMSG_WORLD_LOGIN_TRANSFER_VALUE = 120;
    /**
     * <code>Shared_EO_Messages = 151;</code>
     */
    public static final int Shared_EO_Messages_VALUE = 151;
    /**
     * <pre>
     *Shattered Realm Messages
     * </pre>
     *
     * <code>Shattered_Realm_Messages = 152;</code>
     */
    public static final int Shattered_Realm_Messages_VALUE = 152;
    /**
     * <code>Shattered_Realm_EO_Messages = 251;</code>
     */
    public static final int Shattered_Realm_EO_Messages_VALUE = 251;
    /**
     * <pre>
     *Shattered World Messages
     * </pre>
     *
     * <code>Shattered_World_Messages = 252;</code>
     */
    public static final int Shattered_World_Messages_VALUE = 252;
    /**
     * <code>Shattered_World_EO_Messages = 401;</code>
     */
    public static final int Shattered_World_EO_Messages_VALUE = 401;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Opcode valueOf(int value) {
      return forNumber(value);
    }

    public static Opcode forNumber(int value) {
      switch (value) {
        case 0: return INVALID_OPCODE;
        case 1: return U_Messages;
        case 2: return U_Ping;
        case 3: return U_ServerPerformance;
        case 27: return U_EO_Messages;
        case 28: return Proxy_Messages;
        case 29: return P_OpenConnection;
        case 30: return P_CloseConnection;
        case 31: return P_ServerAvailability;
        case 32: return P_TransmitAccount;
        case 33: return P_RequestRealm;
        case 34: return P_TransferConnection;
        case 35: return P_ServerTransferResponse;
        case 36: return P_RequestNewTransferConnection;
        case 37: return P_TransferToWorld;
        case 38: return P_TransferToRealm;
        case 39: return P_TransferWorldToRealm;
        case 40: return P_WorldCharacterInformation;
        case 51: return Proxy_EO_Messages;
        case 52: return Sharding_Messages;
        case 53: return S_Register;
        case 54: return S_Unregister;
        case 55: return S_ConnectionInfo;
        case 56: return S_RequestConnectionInfo;
        case 57: return S_OpenConnection;
        case 58: return S_WorldInformation;
        case 59: return S_UpdateWorldList;
        case 60: return S_UpdateWorldEntry;
        case 76: return Sharding_EO_Messages;
        case 77: return Channel_Messages;
        case 101: return Channel_EO_Messages;
        case 102: return Shared_Messages;
        case 103: return SMSG_CONNECTED;
        case 104: return SMSG_DISCONNECTED;
        case 105: return SMSG_ACCOUNT_INFORMATION;
        case 106: return CMSG_LOGIN_REQUEST;
        case 107: return SMSG_LOGIN_RESPONSE;
        case 108: return CMSG_REQUEST_LOGOUT;
        case 109: return SMSG_LOGOUT;
        case 110: return SMSG_LOGOUT_WITH_RESPONSE;
        case 111: return CMSG_REQUEST_FRIENDS;
        case 112: return CMSG_FRIENDS_LIST;
        case 113: return CMSG_PRIVATE_MESSAGE;
        case 114: return SMSG_PRIVATE_MESSAGE;
        case 115: return SMSG_FRIENDS_LIST;
        case 116: return SMSG_UPDATE_FRIEND;
        case 117: return CMSG_ADD_FRIEND;
        case 118: return CMSG_REMOVE_FRIEND;
        case 119: return CMSG_IGNORE_CHARACTER;
        case 120: return SMSG_WORLD_LOGIN_TRANSFER;
        case 151: return Shared_EO_Messages;
        case 152: return Shattered_Realm_Messages;
        case 251: return Shattered_Realm_EO_Messages;
        case 252: return Shattered_World_Messages;
        case 401: return Shattered_World_EO_Messages;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Opcode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Opcode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Opcode>() {
            public Opcode findValueByNumber(int number) {
              return Opcode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.shattered.networking.proto.PacketOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Opcode[] VALUES = values();

    public static Opcode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Opcode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:shattered.protocol.Opcode)
  }

  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shattered.protocol.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.shattered.protocol.Opcode opcode = 1;</code>
     */
    int getOpcodeValue();
    /**
     * <code>.shattered.protocol.Opcode opcode = 1;</code>
     */
    com.shattered.networking.proto.PacketOuterClass.Opcode getOpcode();

    /**
     * <code>bytes payload = 2;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code shattered.protocol.Packet}
   */
  public  static final class Packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:shattered.protocol.Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      opcode_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              opcode_ = rawValue;
              break;
            }
            case 18: {

              payload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shattered.networking.proto.PacketOuterClass.Packet.class, com.shattered.networking.proto.PacketOuterClass.Packet.Builder.class);
    }

    public static final int OPCODE_FIELD_NUMBER = 1;
    private int opcode_;
    /**
     * <code>.shattered.protocol.Opcode opcode = 1;</code>
     */
    public int getOpcodeValue() {
      return opcode_;
    }
    /**
     * <code>.shattered.protocol.Opcode opcode = 1;</code>
     */
    public com.shattered.networking.proto.PacketOuterClass.Opcode getOpcode() {
      @SuppressWarnings("deprecation")
      com.shattered.networking.proto.PacketOuterClass.Opcode result = com.shattered.networking.proto.PacketOuterClass.Opcode.valueOf(opcode_);
      return result == null ? com.shattered.networking.proto.PacketOuterClass.Opcode.UNRECOGNIZED : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 2;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (opcode_ != com.shattered.networking.proto.PacketOuterClass.Opcode.INVALID_OPCODE.getNumber()) {
        output.writeEnum(1, opcode_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(2, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (opcode_ != com.shattered.networking.proto.PacketOuterClass.Opcode.INVALID_OPCODE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, opcode_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.shattered.networking.proto.PacketOuterClass.Packet)) {
        return super.equals(obj);
      }
      com.shattered.networking.proto.PacketOuterClass.Packet other = (com.shattered.networking.proto.PacketOuterClass.Packet) obj;

      boolean result = true;
      result = result && opcode_ == other.opcode_;
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPCODE_FIELD_NUMBER;
      hash = (53 * hash) + opcode_;
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.shattered.networking.proto.PacketOuterClass.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shattered.networking.proto.PacketOuterClass.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shattered.networking.proto.PacketOuterClass.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shattered.networking.proto.PacketOuterClass.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.shattered.networking.proto.PacketOuterClass.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.shattered.networking.proto.PacketOuterClass.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.shattered.networking.proto.PacketOuterClass.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.shattered.networking.proto.PacketOuterClass.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code shattered.protocol.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:shattered.protocol.Packet)
        com.shattered.networking.proto.PacketOuterClass.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_Packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shattered.networking.proto.PacketOuterClass.Packet.class, com.shattered.networking.proto.PacketOuterClass.Packet.Builder.class);
      }

      // Construct using com.shattered.networking.proto.PacketOuterClass.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        opcode_ = 0;

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_Packet_descriptor;
      }

      @java.lang.Override
      public com.shattered.networking.proto.PacketOuterClass.Packet getDefaultInstanceForType() {
        return com.shattered.networking.proto.PacketOuterClass.Packet.getDefaultInstance();
      }

      @java.lang.Override
      public com.shattered.networking.proto.PacketOuterClass.Packet build() {
        com.shattered.networking.proto.PacketOuterClass.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.shattered.networking.proto.PacketOuterClass.Packet buildPartial() {
        com.shattered.networking.proto.PacketOuterClass.Packet result = new com.shattered.networking.proto.PacketOuterClass.Packet(this);
        result.opcode_ = opcode_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shattered.networking.proto.PacketOuterClass.Packet) {
          return mergeFrom((com.shattered.networking.proto.PacketOuterClass.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shattered.networking.proto.PacketOuterClass.Packet other) {
        if (other == com.shattered.networking.proto.PacketOuterClass.Packet.getDefaultInstance()) return this;
        if (other.opcode_ != 0) {
          setOpcodeValue(other.getOpcodeValue());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shattered.networking.proto.PacketOuterClass.Packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shattered.networking.proto.PacketOuterClass.Packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int opcode_ = 0;
      /**
       * <code>.shattered.protocol.Opcode opcode = 1;</code>
       */
      public int getOpcodeValue() {
        return opcode_;
      }
      /**
       * <code>.shattered.protocol.Opcode opcode = 1;</code>
       */
      public Builder setOpcodeValue(int value) {
        opcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.shattered.protocol.Opcode opcode = 1;</code>
       */
      public com.shattered.networking.proto.PacketOuterClass.Opcode getOpcode() {
        @SuppressWarnings("deprecation")
        com.shattered.networking.proto.PacketOuterClass.Opcode result = com.shattered.networking.proto.PacketOuterClass.Opcode.valueOf(opcode_);
        return result == null ? com.shattered.networking.proto.PacketOuterClass.Opcode.UNRECOGNIZED : result;
      }
      /**
       * <code>.shattered.protocol.Opcode opcode = 1;</code>
       */
      public Builder setOpcode(com.shattered.networking.proto.PacketOuterClass.Opcode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        opcode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.shattered.protocol.Opcode opcode = 1;</code>
       */
      public Builder clearOpcode() {
        
        opcode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 2;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 2;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:shattered.protocol.Packet)
    }

    // @@protoc_insertion_point(class_scope:shattered.protocol.Packet)
    private static final com.shattered.networking.proto.PacketOuterClass.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.shattered.networking.proto.PacketOuterClass.Packet();
    }

    public static com.shattered.networking.proto.PacketOuterClass.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @java.lang.Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.shattered.networking.proto.PacketOuterClass.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shattered.protocol.EmptyPayload)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code shattered.protocol.EmptyPayload}
   */
  public  static final class EmptyPayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:shattered.protocol.EmptyPayload)
      EmptyPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmptyPayload.newBuilder() to construct.
    private EmptyPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmptyPayload() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmptyPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_EmptyPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_EmptyPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shattered.networking.proto.PacketOuterClass.EmptyPayload.class, com.shattered.networking.proto.PacketOuterClass.EmptyPayload.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.shattered.networking.proto.PacketOuterClass.EmptyPayload)) {
        return super.equals(obj);
      }
      com.shattered.networking.proto.PacketOuterClass.EmptyPayload other = (com.shattered.networking.proto.PacketOuterClass.EmptyPayload) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.shattered.networking.proto.PacketOuterClass.EmptyPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code shattered.protocol.EmptyPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:shattered.protocol.EmptyPayload)
        com.shattered.networking.proto.PacketOuterClass.EmptyPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_EmptyPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_EmptyPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shattered.networking.proto.PacketOuterClass.EmptyPayload.class, com.shattered.networking.proto.PacketOuterClass.EmptyPayload.Builder.class);
      }

      // Construct using com.shattered.networking.proto.PacketOuterClass.EmptyPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_EmptyPayload_descriptor;
      }

      @java.lang.Override
      public com.shattered.networking.proto.PacketOuterClass.EmptyPayload getDefaultInstanceForType() {
        return com.shattered.networking.proto.PacketOuterClass.EmptyPayload.getDefaultInstance();
      }

      @java.lang.Override
      public com.shattered.networking.proto.PacketOuterClass.EmptyPayload build() {
        com.shattered.networking.proto.PacketOuterClass.EmptyPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.shattered.networking.proto.PacketOuterClass.EmptyPayload buildPartial() {
        com.shattered.networking.proto.PacketOuterClass.EmptyPayload result = new com.shattered.networking.proto.PacketOuterClass.EmptyPayload(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shattered.networking.proto.PacketOuterClass.EmptyPayload) {
          return mergeFrom((com.shattered.networking.proto.PacketOuterClass.EmptyPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shattered.networking.proto.PacketOuterClass.EmptyPayload other) {
        if (other == com.shattered.networking.proto.PacketOuterClass.EmptyPayload.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shattered.networking.proto.PacketOuterClass.EmptyPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shattered.networking.proto.PacketOuterClass.EmptyPayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:shattered.protocol.EmptyPayload)
    }

    // @@protoc_insertion_point(class_scope:shattered.protocol.EmptyPayload)
    private static final com.shattered.networking.proto.PacketOuterClass.EmptyPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.shattered.networking.proto.PacketOuterClass.EmptyPayload();
    }

    public static com.shattered.networking.proto.PacketOuterClass.EmptyPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmptyPayload>
        PARSER = new com.google.protobuf.AbstractParser<EmptyPayload>() {
      @java.lang.Override
      public EmptyPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmptyPayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmptyPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmptyPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.shattered.networking.proto.PacketOuterClass.EmptyPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StringPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shattered.protocol.StringPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string payload = 1;</code>
     */
    java.lang.String getPayload();
    /**
     * <code>string payload = 1;</code>
     */
    com.google.protobuf.ByteString
        getPayloadBytes();
  }
  /**
   * Protobuf type {@code shattered.protocol.StringPayload}
   */
  public  static final class StringPayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:shattered.protocol.StringPayload)
      StringPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StringPayload.newBuilder() to construct.
    private StringPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StringPayload() {
      payload_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StringPayload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              payload_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_StringPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_StringPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.shattered.networking.proto.PacketOuterClass.StringPayload.class, com.shattered.networking.proto.PacketOuterClass.StringPayload.Builder.class);
    }

    public static final int PAYLOAD_FIELD_NUMBER = 1;
    private volatile java.lang.Object payload_;
    /**
     * <code>string payload = 1;</code>
     */
    public java.lang.String getPayload() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payload_ = s;
        return s;
      }
    }
    /**
     * <code>string payload = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPayloadBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPayloadBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.shattered.networking.proto.PacketOuterClass.StringPayload)) {
        return super.equals(obj);
      }
      com.shattered.networking.proto.PacketOuterClass.StringPayload other = (com.shattered.networking.proto.PacketOuterClass.StringPayload) obj;

      boolean result = true;
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.shattered.networking.proto.PacketOuterClass.StringPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.shattered.networking.proto.PacketOuterClass.StringPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code shattered.protocol.StringPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:shattered.protocol.StringPayload)
        com.shattered.networking.proto.PacketOuterClass.StringPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_StringPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_StringPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.shattered.networking.proto.PacketOuterClass.StringPayload.class, com.shattered.networking.proto.PacketOuterClass.StringPayload.Builder.class);
      }

      // Construct using com.shattered.networking.proto.PacketOuterClass.StringPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        payload_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.shattered.networking.proto.PacketOuterClass.internal_static_shattered_protocol_StringPayload_descriptor;
      }

      @java.lang.Override
      public com.shattered.networking.proto.PacketOuterClass.StringPayload getDefaultInstanceForType() {
        return com.shattered.networking.proto.PacketOuterClass.StringPayload.getDefaultInstance();
      }

      @java.lang.Override
      public com.shattered.networking.proto.PacketOuterClass.StringPayload build() {
        com.shattered.networking.proto.PacketOuterClass.StringPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.shattered.networking.proto.PacketOuterClass.StringPayload buildPartial() {
        com.shattered.networking.proto.PacketOuterClass.StringPayload result = new com.shattered.networking.proto.PacketOuterClass.StringPayload(this);
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.shattered.networking.proto.PacketOuterClass.StringPayload) {
          return mergeFrom((com.shattered.networking.proto.PacketOuterClass.StringPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.shattered.networking.proto.PacketOuterClass.StringPayload other) {
        if (other == com.shattered.networking.proto.PacketOuterClass.StringPayload.getDefaultInstance()) return this;
        if (!other.getPayload().isEmpty()) {
          payload_ = other.payload_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.shattered.networking.proto.PacketOuterClass.StringPayload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.shattered.networking.proto.PacketOuterClass.StringPayload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object payload_ = "";
      /**
       * <code>string payload = 1;</code>
       */
      public java.lang.String getPayload() {
        java.lang.Object ref = payload_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          payload_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string payload = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPayloadBytes() {
        java.lang.Object ref = payload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string payload = 1;</code>
       */
      public Builder setPayload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string payload = 1;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      /**
       * <code>string payload = 1;</code>
       */
      public Builder setPayloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        payload_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:shattered.protocol.StringPayload)
    }

    // @@protoc_insertion_point(class_scope:shattered.protocol.StringPayload)
    private static final com.shattered.networking.proto.PacketOuterClass.StringPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.shattered.networking.proto.PacketOuterClass.StringPayload();
    }

    public static com.shattered.networking.proto.PacketOuterClass.StringPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StringPayload>
        PARSER = new com.google.protobuf.AbstractParser<StringPayload>() {
      @java.lang.Override
      public StringPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringPayload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StringPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StringPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.shattered.networking.proto.PacketOuterClass.StringPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shattered_protocol_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shattered_protocol_Packet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shattered_protocol_EmptyPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shattered_protocol_EmptyPayload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shattered_protocol_StringPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shattered_protocol_StringPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014packet.proto\022\022shattered.protocol\"E\n\006Pa" +
      "cket\022*\n\006opcode\030\001 \001(\0162\032.shattered.protoco" +
      "l.Opcode\022\017\n\007payload\030\002 \001(\014\"\016\n\014EmptyPayloa" +
      "d\" \n\rStringPayload\022\017\n\007payload\030\001 \001(\t*\341\n\n\006" +
      "Opcode\022\022\n\016INVALID_OPCODE\020\000\022\016\n\nU_Messages" +
      "\020\001\022\n\n\006U_Ping\020\002\022\027\n\023U_ServerPerformance\020\003\022" +
      "\021\n\rU_EO_Messages\020\033\022\022\n\016Proxy_Messages\020\034\022\024" +
      "\n\020P_OpenConnection\020\035\022\025\n\021P_CloseConnectio" +
      "n\020\036\022\030\n\024P_ServerAvailability\020\037\022\025\n\021P_Trans" +
      "mitAccount\020 \022\022\n\016P_RequestRealm\020!\022\030\n\024P_Tr" +
      "ansferConnection\020\"\022\034\n\030P_ServerTransferRe" +
      "sponse\020#\022\"\n\036P_RequestNewTransferConnecti" +
      "on\020$\022\025\n\021P_TransferToWorld\020%\022\025\n\021P_Transfe" +
      "rToRealm\020&\022\032\n\026P_TransferWorldToRealm\020\'\022\037" +
      "\n\033P_WorldCharacterInformation\020(\022\025\n\021Proxy" +
      "_EO_Messages\0203\022\025\n\021Sharding_Messages\0204\022\016\n" +
      "\nS_Register\0205\022\020\n\014S_Unregister\0206\022\024\n\020S_Con" +
      "nectionInfo\0207\022\033\n\027S_RequestConnectionInfo" +
      "\0208\022\024\n\020S_OpenConnection\0209\022\026\n\022S_WorldInfor" +
      "mation\020:\022\025\n\021S_UpdateWorldList\020;\022\026\n\022S_Upd" +
      "ateWorldEntry\020<\022\030\n\024Sharding_EO_Messages\020" +
      "L\022\024\n\020Channel_Messages\020M\022\027\n\023Channel_EO_Me" +
      "ssages\020e\022\023\n\017Shared_Messages\020f\022\022\n\016SMSG_CO" +
      "NNECTED\020g\022\025\n\021SMSG_DISCONNECTED\020h\022\034\n\030SMSG" +
      "_ACCOUNT_INFORMATION\020i\022\026\n\022CMSG_LOGIN_REQ" +
      "UEST\020j\022\027\n\023SMSG_LOGIN_RESPONSE\020k\022\027\n\023CMSG_" +
      "REQUEST_LOGOUT\020l\022\017\n\013SMSG_LOGOUT\020m\022\035\n\031SMS" +
      "G_LOGOUT_WITH_RESPONSE\020n\022\030\n\024CMSG_REQUEST" +
      "_FRIENDS\020o\022\025\n\021CMSG_FRIENDS_LIST\020p\022\030\n\024CMS" +
      "G_PRIVATE_MESSAGE\020q\022\030\n\024SMSG_PRIVATE_MESS" +
      "AGE\020r\022\025\n\021SMSG_FRIENDS_LIST\020s\022\026\n\022SMSG_UPD" +
      "ATE_FRIEND\020t\022\023\n\017CMSG_ADD_FRIEND\020u\022\026\n\022CMS" +
      "G_REMOVE_FRIEND\020v\022\031\n\025CMSG_IGNORE_CHARACT" +
      "ER\020w\022\035\n\031SMSG_WORLD_LOGIN_TRANSFER\020x\022\027\n\022S" +
      "hared_EO_Messages\020\227\001\022\035\n\030Shattered_Realm_" +
      "Messages\020\230\001\022 \n\033Shattered_Realm_EO_Messag" +
      "es\020\373\001\022\035\n\030Shattered_World_Messages\020\374\001\022 \n\033" +
      "Shattered_World_EO_Messages\020\221\003\"\004\010\004\020\032\"\004\010)" +
      "\0202\"\004\010=\020K\"\005\010y\020\226\001B#\n\036com.shattered.network" +
      "ing.proto\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_shattered_protocol_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_shattered_protocol_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shattered_protocol_Packet_descriptor,
        new java.lang.String[] { "Opcode", "Payload", });
    internal_static_shattered_protocol_EmptyPayload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_shattered_protocol_EmptyPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shattered_protocol_EmptyPayload_descriptor,
        new java.lang.String[] { });
    internal_static_shattered_protocol_StringPayload_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_shattered_protocol_StringPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shattered_protocol_StringPayload_descriptor,
        new java.lang.String[] { "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
